from datetime import time
from decimal import Decimal
from django.db import migrations


def seed_doctors(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    DoctorProfile = apps.get_model('accounts', 'DoctorProfile')
    doctor_definitions = [
        {
            'username': 'asha.patel@demo.com',
            'first_name': 'Asha',
            'last_name': 'Patel',
            'phone': '555010001',
            'specialization': 'cardiology',
            'license_number': 'CARD-24-001',
            'experience_years': 14,
            'hospital_name': 'Summit Heart Institute',
            'consultation_fee': Decimal('220.00'),
            'available_from': time(0, 0),
            'available_to': time(8, 0),
            'rating': 4.9,
        },
        {
            'username': 'miguel.reyes@demo.com',
            'first_name': 'Miguel',
            'last_name': 'Reyes',
            'phone': '555010002',
            'specialization': 'cardiology',
            'license_number': 'CARD-24-002',
            'experience_years': 11,
            'hospital_name': 'Summit Heart Institute',
            'consultation_fee': Decimal('210.00'),
            'available_from': time(8, 0),
            'available_to': time(16, 0),
            'rating': 4.7,
        },
        {
            'username': 'lauren.chen@demo.com',
            'first_name': 'Lauren',
            'last_name': 'Chen',
            'phone': '555010003',
            'specialization': 'cardiology',
            'license_number': 'CARD-24-003',
            'experience_years': 9,
            'hospital_name': 'Summit Heart Institute',
            'consultation_fee': Decimal('205.00'),
            'available_from': time(16, 0),
            'available_to': time(23, 59),
            'rating': 4.8,
        },
        {
            'username': 'priya.khanna@demo.com',
            'first_name': 'Priya',
            'last_name': 'Khanna',
            'phone': '555020001',
            'specialization': 'dermatology',
            'license_number': 'DERM-24-001',
            'experience_years': 10,
            'hospital_name': 'Radiant Skin Center',
            'consultation_fee': Decimal('160.00'),
            'available_from': time(0, 0),
            'available_to': time(8, 0),
            'rating': 4.9,
        },
        {
            'username': 'aaron.brooks@demo.com',
            'first_name': 'Aaron',
            'last_name': 'Brooks',
            'phone': '555020002',
            'specialization': 'dermatology',
            'license_number': 'DERM-24-002',
            'experience_years': 12,
            'hospital_name': 'Radiant Skin Center',
            'consultation_fee': Decimal('180.00'),
            'available_from': time(8, 0),
            'available_to': time(16, 0),
            'rating': 4.6,
        },
        {
            'username': 'elise.dubois@demo.com',
            'first_name': 'Elise',
            'last_name': 'Dubois',
            'phone': '555020003',
            'specialization': 'dermatology',
            'license_number': 'DERM-24-003',
            'experience_years': 8,
            'hospital_name': 'Radiant Skin Center',
            'consultation_fee': Decimal('155.00'),
            'available_from': time(16, 0),
            'available_to': time(23, 59),
            'rating': 4.8,
        },
        {
            'username': 'kavita.menon@demo.com',
            'first_name': 'Kavita',
            'last_name': 'Menon',
            'phone': '555030001',
            'specialization': 'neurology',
            'license_number': 'NEUR-24-001',
            'experience_years': 15,
            'hospital_name': 'NeuroCare Institute',
            'consultation_fee': Decimal('240.00'),
            'available_from': time(0, 0),
            'available_to': time(8, 0),
            'rating': 4.9,
        },
        {
            'username': 'daniel.harper@demo.com',
            'first_name': 'Daniel',
            'last_name': 'Harper',
            'phone': '555030002',
            'specialization': 'neurology',
            'license_number': 'NEUR-24-002',
            'experience_years': 13,
            'hospital_name': 'NeuroCare Institute',
            'consultation_fee': Decimal('230.00'),
            'available_from': time(8, 0),
            'available_to': time(16, 0),
            'rating': 4.7,
        },
        {
            'username': 'sofia.rinaldi@demo.com',
            'first_name': 'Sofia',
            'last_name': 'Rinaldi',
            'phone': '555030003',
            'specialization': 'neurology',
            'license_number': 'NEUR-24-003',
            'experience_years': 9,
            'hospital_name': 'NeuroCare Institute',
            'consultation_fee': Decimal('225.00'),
            'available_from': time(16, 0),
            'available_to': time(23, 59),
            'rating': 4.8,
        },
        {
            'username': 'lily.evans@demo.com',
            'first_name': 'Lily',
            'last_name': 'Evans',
            'phone': '555040001',
            'specialization': 'pediatrics',
            'license_number': 'PEDS-24-001',
            'experience_years': 11,
            'hospital_name': "BrightStart Children's Hospital",
            'consultation_fee': Decimal('140.00'),
            'available_from': time(0, 0),
            'available_to': time(8, 0),
            'rating': 4.8,
        },
        {
            'username': 'omar.siddiqi@demo.com',
            'first_name': 'Omar',
            'last_name': 'Siddiqi',
            'phone': '555040002',
            'specialization': 'pediatrics',
            'license_number': 'PEDS-24-002',
            'experience_years': 9,
            'hospital_name': "BrightStart Children's Hospital",
            'consultation_fee': Decimal('135.00'),
            'available_from': time(8, 0),
            'available_to': time(16, 0),
            'rating': 4.7,
        },
        {
            'username': 'hannah.morales@demo.com',
            'first_name': 'Hannah',
            'last_name': 'Morales',
            'phone': '555040003',
            'specialization': 'pediatrics',
            'license_number': 'PEDS-24-003',
            'experience_years': 7,
            'hospital_name': "BrightStart Children's Hospital",
            'consultation_fee': Decimal('130.00'),
            'available_from': time(16, 0),
            'available_to': time(23, 59),
            'rating': 4.6,
        },
        {
            'username': 'jason.wu@demo.com',
            'first_name': 'Jason',
            'last_name': 'Wu',
            'phone': '555050001',
            'specialization': 'orthopedics',
            'license_number': 'ORTH-24-001',
            'experience_years': 13,
            'hospital_name': 'Flexion Orthopedic Center',
            'consultation_fee': Decimal('200.00'),
            'available_from': time(0, 0),
            'available_to': time(8, 0),
            'rating': 4.8,
        },
        {
            'username': 'emily.rhodes@demo.com',
            'first_name': 'Emily',
            'last_name': 'Rhodes',
            'phone': '555050002',
            'specialization': 'orthopedics',
            'license_number': 'ORTH-24-002',
            'experience_years': 12,
            'hospital_name': 'Flexion Orthopedic Center',
            'consultation_fee': Decimal('210.00'),
            'available_from': time(8, 0),
            'available_to': time(16, 0),
            'rating': 4.7,
        },
        {
            'username': 'naveen.iyer@demo.com',
            'first_name': 'Naveen',
            'last_name': 'Iyer',
            'phone': '555050003',
            'specialization': 'orthopedics',
            'license_number': 'ORTH-24-003',
            'experience_years': 10,
            'hospital_name': 'Flexion Orthopedic Center',
            'consultation_fee': Decimal('205.00'),
            'available_from': time(16, 0),
            'available_to': time(23, 59),
            'rating': 4.7,
        },
        {
            'username': 'maria.gomez@demo.com',
            'first_name': 'Maria',
            'last_name': 'Gomez',
            'phone': '555060001',
            'specialization': 'general',
            'license_number': 'GEN-24-001',
            'experience_years': 16,
            'hospital_name': 'Unity Family Clinic',
            'consultation_fee': Decimal('120.00'),
            'available_from': time(0, 0),
            'available_to': time(8, 0),
            'rating': 4.9,
        },
        {
            'username': 'caleb.foster@demo.com',
            'first_name': 'Caleb',
            'last_name': 'Foster',
            'phone': '555060002',
            'specialization': 'general',
            'license_number': 'GEN-24-002',
            'experience_years': 12,
            'hospital_name': 'Unity Family Clinic',
            'consultation_fee': Decimal('110.00'),
            'available_from': time(8, 0),
            'available_to': time(16, 0),
            'rating': 4.7,
        },
        {
            'username': 'zainab.ali@demo.com',
            'first_name': 'Zainab',
            'last_name': 'Ali',
            'phone': '555060003',
            'specialization': 'general',
            'license_number': 'GEN-24-003',
            'experience_years': 8,
            'hospital_name': 'Unity Family Clinic',
            'consultation_fee': Decimal('105.00'),
            'available_from': time(16, 0),
            'available_to': time(23, 59),
            'rating': 4.6,
        },
        {
            'username': 'nisha.verma@demo.com',
            'first_name': 'Nisha',
            'last_name': 'Verma',
            'phone': '555070001',
            'specialization': 'psychiatry',
            'license_number': 'PSY-24-001',
            'experience_years': 13,
            'hospital_name': 'Mindful Horizons Center',
            'consultation_fee': Decimal('180.00'),
            'available_from': time(0, 0),
            'available_to': time(8, 0),
            'rating': 4.8,
        },
        {
            'username': 'david.cho@demo.com',
            'first_name': 'David',
            'last_name': 'Cho',
            'phone': '555070002',
            'specialization': 'psychiatry',
            'license_number': 'PSY-24-002',
            'experience_years': 11,
            'hospital_name': 'Mindful Horizons Center',
            'consultation_fee': Decimal('175.00'),
            'available_from': time(8, 0),
            'available_to': time(16, 0),
            'rating': 4.7,
        },
        {
            'username': 'amelia.grant@demo.com',
            'first_name': 'Amelia',
            'last_name': 'Grant',
            'phone': '555070003',
            'specialization': 'psychiatry',
            'license_number': 'PSY-24-003',
            'experience_years': 9,
            'hospital_name': 'Mindful Horizons Center',
            'consultation_fee': Decimal('170.00'),
            'available_from': time(16, 0),
            'available_to': time(23, 59),
            'rating': 4.6,
        },
    ]
    for entry in doctor_definitions:
        user, created = User.objects.get_or_create(
            username=entry['username'],
            defaults={
                'email': entry['username'],
                'first_name': entry['first_name'],
                'last_name': entry['last_name'],
                'phone': entry['phone'],
                'role': 'doctor',
            },
        )
        user.email = entry['username']
        user.first_name = entry['first_name']
        user.last_name = entry['last_name']
        user.phone = entry['phone']
        user.role = 'doctor'
        user.is_verified = True
        user.set_password('Doctor123!')
        user.save()
        DoctorProfile.objects.update_or_create(
            user=user,
            defaults={
                'specialization': entry['specialization'],
                'license_number': entry['license_number'],
                'experience_years': entry['experience_years'],
                'hospital_name': entry['hospital_name'],
                'consultation_fee': entry['consultation_fee'],
                'available_from': entry['available_from'],
                'available_to': entry['available_to'],
                'is_approved': True,
                'rating': entry['rating'],
                'total_appointments': 0,
            },
        )


def unseed_doctors(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    usernames = [
        'asha.patel@demo.com',
        'miguel.reyes@demo.com',
        'lauren.chen@demo.com',
        'priya.khanna@demo.com',
        'aaron.brooks@demo.com',
        'elise.dubois@demo.com',
        'kavita.menon@demo.com',
        'daniel.harper@demo.com',
        'sofia.rinaldi@demo.com',
        'lily.evans@demo.com',
        'omar.siddiqi@demo.com',
        'hannah.morales@demo.com',
        'jason.wu@demo.com',
        'emily.rhodes@demo.com',
        'naveen.iyer@demo.com',
        'maria.gomez@demo.com',
        'caleb.foster@demo.com',
        'zainab.ali@demo.com',
        'nisha.verma@demo.com',
        'david.cho@demo.com',
        'amelia.grant@demo.com',
    ]
    User.objects.filter(username__in=usernames).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_doctors, unseed_doctors),
    ]
