# Generated by Django 4.2.7 on 2025-11-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_sample_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='total_appointments',
            new_name='total_appointments_field',
        ),
    ]
