# Generated by Django 4.2.7 on 2025-11-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_total_appointments_doctorprofile_total_appointments_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='total_appointments_field',
        ),
    ]
