# Generated by Django 4.2.7 on 2025-11-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_doctorprofile_total_appointments_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='total_appointments',
            field=models.IntegerField(default=0),
        ),
    ]
