# Generated by Django 4.2.7 on 2025-10-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_request', 'Appointment Request'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_completed', 'Appointment Completed'), ('appointment_cancelled', 'Appointment Cancelled'), ('message', 'New Message'), ('doctor_approved', 'Doctor Approved')], max_length=50),
        ),
    ]
