# Generated by Django 4.2.7 on 2025-11-09 17:39
# This migration is a no-op as DoctorProfile is imported from accounts app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_prescriptiontemplate_prescriptiontemplateitem_and_more'),
    ]

    operations = [
    ]
